// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package online_shop

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrderByUsernameProductnameAndQuantityFirst(ctx context.Context, arg CreateOrderByUsernameProductnameAndQuantityFirstParams) (*string, error)
	CreateOrderByUsernameProductnameAndQuantitySecond(ctx context.Context, name string) (pgtype.UUID, error)
	DeleteOrderByUsername(ctx context.Context, name string) (*string, error)
	DeleteProductByName(ctx context.Context, name string) (pgtype.UUID, error)
	DeleteUserByName(ctx context.Context, name string) (pgtype.UUID, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (pgtype.UUID, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error)
	SelectOrdersByUsername(ctx context.Context, name string) ([]*SelectOrdersByUsernameRow, error)
	SelectProductsByPrices(ctx context.Context, arg SelectProductsByPricesParams) ([]string, error)
	SelectTwoUsersByUsername(ctx context.Context, arg SelectTwoUsersByUsernameParams) ([]*User, error)
	SelectUsersByOrders(ctx context.Context) ([]*SelectUsersByOrdersRow, error)
	UpdateProductpriceByName(ctx context.Context, arg UpdateProductpriceByNameParams) (pgtype.UUID, error)
	UpdateUsernameByName(ctx context.Context, arg UpdateUsernameByNameParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
