services:
  hw-app:
    build: ./
    depends_on: 
      - pg-storage
    ports:
      - 8080:8080

  pg-storage:
      restart: always
      image: postgres:16.2-alpine
      environment:
          POSTGRES_DB: storage
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: developer
          PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ../../localdata/pg-storage:/var/lib/postgresql/data
      ports:
        - 65431:5432